Simu_Para:
  user_name: 'yanghang'
  # Choose the program mode
  program: 'trans'  # trans, ai_algo
  # Path
  run_id: '000' #  '000' and 'test' for Test
  exp_align_config_path: '/Share/Code/IFTS/main/trans/simulation/config/data/'
  len_config_path:  '/Share/Code/IFTS/main/trans/experiment/config/span_len.yml'
  result_root_path: '/Personal/Yanghang/Results/IFTS/'
  awg_root_path: '/home/ospan/AWG_load_data/'
  save_data_root_path: '/Share/Data/'
  dsp_mode : ['tradition', 'tradition'] # vanilla, tradition, learned
  time_record: 1
  # sam_rate
  awg_memory_depth: 65536    # 262144 131072
  tx_sam_rate: 196.8 # 80 Gsam/sec for Fujistu 
  rx_sam_rate: 196.8 # 100 Gsam/sec for Tec
  # data load information
  run_tx_dsp: 1        # 1: generate data by program; 0: load data from file if needed
  run_dac: 1           # 1: run AWG; 0: run 'resample' in the simulation or stop at 'tx_dsp' in the experiment
  run_ch: 1            # 1: input to channel; 0: stop at tx
  run_adc: 1           # 1: run Oscope; 0: load data from file
  run_rx_dsp: 0        # 1: load data from file; 0: generate data by program
  set_edfa: 0
  is_ase: 0
  is_bidi: 0
  is_b2b: 0
  calcu_osnr: 0 
  # expriments information
  sym_rate: 98.4 # GHz
  bits_per_sym: 4
  nPol: 2
  sig_power_dbm : 4.0
  channel_num : 1 # index of channel under test 
  # control for sig, tx, rx
  # sig
  coding : 0
  do_pcs : 1
  pcs_mi : 2.75
  modulation : 1
  nn_modu : 0 
  nn_demodu : 0
  demodulation : 1
  decoding : 0
  # tx
  pulse_shaping: 1
  pre_cdcom : 0
  pre_emph : 0
  skew_eq : 0
  tx_nn_eq : 0
  clock_leakage: 0
  clipping: 0
  quantization: 0

  # DT
  DT: 0   #whether process DT,after tx,before channel
  # if DT == 1,tx and sig setting should be consistent with the training model condition
  # version now only use the symbol after shaping

  # ch
  scm: 0
  ch_upsam: 4
  dac : 0
  transmitter : 0
  wss : 1
  laser : 0
  tx_amp : 0
  rx_amp : 0
  channel_type : 1  # 0:Experiments, 1: Simu_fiber, 2: Simu_AWGN
  do_cdm : 0        
  span_num: 10
  load_len: 0       # 1: read span_len.yml 0: set a constant = span_len
  span_len : 80     # 
  total_len : 800    # 
  channel_space : 100
  receiver : 0
  adc : 0
  # rx
  lpf : 0
  ckl_com : 0
  iq_balance: 0
  iq_deskew: 0
  nl_com : 0
  cdcom : 1  #不能关闭，para会报错
  mimo : 0   #mimo打开有问题，XY会更加混乱，输出崩溃
  real_mimo : 0
  symchronization : 1
  cpe : 0
  clofo : 0
  # Others
  modulation_list : {'2': 'QPSK', '3': '8QAM', '4': '16QAM', '5':'32QAM', '6': '64QAM'}
  caclu_with_gpu : 1
  data_mode : 'hybrid'   # numpy, torch, hybrid, config_assign
  device: "cuda:4"
  torch_data_type: 'double'  # double float
  infor_print_arr : [1, 1, 1, 1]
  fig_plot_arr : [0, 0, 1, 1]
  save_data_arr : [0, 0, 0, 0]
  log_verbosity : 3     # 3 (DEBUG) < 2 (INFO) < 1 (WARNING) < 0 (ERROR)
  # link manage
  do_link_manage : 0
  cd_manage_arr : [-80.,30.,-35.,40.,0.,0. ]

Sig_Para:
  rand_seed: 1112
  bit_load : 0
  front_sym_num: 2048
  
  # probalisitic shaping configuration
  pcs_config:
    mode: 'MB'
    args:
      do_ccdm: 0  # open flag for CCDM

  # demodulation configuration
  demod_config:
    mode: 'llr' # 'bit', 'int', 'llr', or 'approxllr'
    data_mode: 'numpy'

DT_Para:
  # do_NL_fiber: 0       #无需做非线性运算
  load_exp_data: 1     #是否加载试验数据tx与rx symbols;加载数据的话
  #加载试验数据方便和EXP数据比较

Ch_Para:
  rand_seed: 8710 # control random seed
  
  dac_config:
    mode: 'no_filter'  # brickwall, bessel, butter, no filter
    args:
      resolution: 8
      rclip: 0                  # clipping ratio.
  
  adc_config:
    mode: 'no_filter'  # brickwall, bessel, butter, no filter
    args:
      resolution: 8
      rclip: 0                  # clipping ratio.

  wsm_config:     # multiplexing
    mode: 'brickwall_filter'  # brickwall_filter, wss_filter
    args:
      sig_p_align: 0 
      sig_p_per_ch: -13  # signal out power dBm
  
  wsd_config:     # demultiplexing
    mode: 'brickwall_filter'  # brickwall_filter, wss_filter
    args:
      sig_p_per_ch: 0   # signal out power dBm

  tx_laser_config:
    mode: 'naive'
    args:
      rand_seed: 15673
      laser_width: 0.26 # MHz
      lofo: 0.6 # GHz

  rx_laser_config:
    mode: 'naive'
    args:
      rand_seed: 78932
      laser_width: 0.0 # MHz
      lofo: 0.0 # GHz
  
  tx_edfa_config:
    mode: 'no_noise_pass'  # naive_pass, no_noise_pass
    nf_db: 5 # dB
    rand_seed: 95512

  edfa_config:
    mode: 'no_noise_pass'  # naive_pass, no_noise_pass
    nf_db: 5 # dB
    rand_seed: 84572

  rx_edfa_config:
    mode: 'no_noise_pass'  # naive_pass, no_noise_pass
    nf_db: 5 # dB
    sig_out_p: 0        # dBm 
    rand_seed: 55843

  icr_config:
    mode: 'naive'
    args:
      rand_seed: 36521
      add_noise: 1 
      n_power_dBm: -18.6751 # [-20.6751 -21.6751 -21.7] dBm

  fiber_config:
    rand_seed: 99876
    wavelength: 1550 # nm
    # CD
    D: 17      # CD Parameter. Default: 17 (ps/nm.km)
    S: 0       # CD slope. Default: 0.075  ps/(nm^2.km)
    pmd: 0
    # Loss
    alpha_inndB: 0.2 # Fiber Loss. Default: 0.2
    # Kerr Nonlinearity
    n2: 2.6e-20
    Aeff: 80
    # model algorithm
    mode: 'SSFM'  # SSFM, NN, NLIN
    # mode: 'NN'                                                                                # 光纤信道仿真模式（'SSFM' - 分布傅里叶法, 'NN' - AI信道模型） 
    # nn_model: 'BiLSTM'                                                                        # AI信道模型类型（'GAN','BiLSTM'）,信道仿真模式为'NN'时需要设置参数
    args:
      Manakov: 1    # 1: manakov; 0: CNlSE
      step_config:
        dz_mode: 'np'    # np: Nonlinear Phase, c: Constant Step
        dphimax: 0.005  # Max. nonlinear phase rotation in each step (rad)
      
      pmd_config:
        dgd_manual: 0
        dgd_total: 0.45  # Differential group delay ps [0.16, 8]
        psp_manual: 0
        pmd_coeff_random: 0
        pmd_dz_random: 0
        pmd_coeff: 0.05 # Default: 0.05 ps/sqrt(km); Polarization mode dispersion coefficient. If Birefringence
                        # type is “Stochastic”, this is the value of the PMD
                        # parameter. If “Deterministic”, parameter is disabled. 
                        # [0.0447, 2.236]
        pmd_trunk_num: 80 # wave plates for PMD simulation
        
Tx_Para:
  rand_seed: 2595
  tx_nn_eq : 0
  release_memory: 1
  pulse_shaping_config:
    type: 'rrc'
    args:
      upsam: 4
      roll_off: 0.1
  
  pre_cdcom_config:
    cd_len: 0

  pre_emph_config:
    data_mode: 'torch'
    args:
      s21_path: '/home/Niuzekun/code/tools/v2.0/experiment_main/config/awg_s21.npz'

  cl_com_config: 
    data_mode: 'numpy'

  iq_deskew_config:
    mode: 'freq'
    data_mode: 'numpy'
    args:
      skew_list: [-1.35, 0, -1.0, 0]
  
  clipping_config:
    clipping_ratio: 8.5
  
  quantization_config:
    resolution_bits: 8
    data_gain: [255, 255, 255, 255]      # max value is 255
    data_switch: [1, 1, 1, 1]      # 1 or 0
  
Rx_Para:
  rand_seed: 48561
  frame_num: 1
  sam_rate_bias: 0.0
  ckl_com_config: 
    data_mode: 'numpy'
  iq_deskew_config:
    mode: 'freq'
    data_mode: 'torch'
    args:
      skew_list: [0,0,0,0] 
      # skew_list: [-13.32746592, 13.33457317, -14.12980795, 14.03374108] # old
      # skew_list: [-18.0661049, 18.0876316, -19.9836891, 17.0423810] # new
      # skew_list: [-17.9613804,  18.2110843, -19.8461730, 17.2096270] # new

  lpf_config:
    mode: 'rrc' # brickwall, bessel, butter, gaussian, rc, rrc
    args:
      # filter_bw: 50
      roll_off: 0.1
      max_lofo: 0.5   # GHz
      comp_s21: 0
      s21_path: '/home/Niuzekun/code/tools/v2.0/experiment_main/config/icr_s21.npz'
    
  iq_balance_config:
    type: 'GSOP'

  nl_com_config:
    type: 'DBP'
    args:
      sym_sam: 2
      sps: 50
      nl_coeff: 1
      dz_mode: 'c'

  cd_com_config:
    type: 'FD_2x2'
    # sam_per_sym: 2
    args:
      cdc_length: 'auto'
    
  mimo_config:
    mode: 'TD_2x2'
    half_taps_num: 50  #50
    out_sym_num: 1
    upsam: 2 
    block_size: 64 #64
    err_calcu: 'mean' # mean, individual
    data_mode: 'numpy'
    args:
      algo_type: 'mma'
      h_ortho: 1
      tap_init_mode: 1.0
      tap_init_value: 0.5 #0.5
      cma_pretrain: 1
      pre_train_iter: 1
      # train_num: 4060
      raius_idx: 0
      train_epoch: 6 #6
      lr: 8.0e-7  #2.8e-4 8.0e-6

  clofo_config:
    mode: 'freq_method'  # freq_method
    block_num: 1        
    parallelism: 1
    window_size: 61
    data_mode: 'torch'
    args: {}

  cpe_config:
    mode: 'bps'
    window_size: 41 #41 
    data_mode: 'numpy'
    args:
      ml: 1
      test_num: 8
      data_aided: 1

  synchron_config:
    mode: '4x4'
    corr_num: 512
    data_mode: 'numpy'
    args: {}

  real_mimo_config:
    mode: 'TD_4x4'
    half_taps_num: 30
    out_sym_num: 1
    upsam: 1 
    block_size: 64
    err_calcu: 'mean' # mean, individual
    data_mode: 'numpy'
    args:
      algo_type: 'lms'
      h_ortho: 0
      tap_init_mode: 1
      tap_init_value: 1.0
      cma_pretrain: 0
      pre_train_iter: 0
      train_epoch: 8
      lr: 1.0e-8

Logger_config:
  version: 1 
  disable_existing_loggers: false
  formatters: 
    simple: 
      format: "%(message)s"
    datetime: 
      format: "%(process)s - %(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "simple"
      stream: "ext://sys.stdout"
    info_file_handler: 
      class: "logging.handlers.RotatingFileHandler" 
      level: "INFO"
      formatter: "datetime"
      filename: "info.log"
      maxBytes: 10485760
      backupCount: 20
      encoding: "utf8"
  root: 
    level: "INFO"
    handlers: ["console", "info_file_handler"]